from typing import Protocol


class TodoRepository(Protocol):
    def add(self, item: dict) -> None: ...
    def update(self, item: dict) -> None: ...
    def delete(self, item_id: int) -> None: ...
    def get_by_id(self, item_id: int) -> dict | None: ...
    def list_all(self) -> list[dict]: ...
